class ClinicModel {

    "UF": "AC",
    "CIDADE": "RIO BRANCO",
    "BAIRRO-REF": "BOSQUE",
    "NOME-REF": "CEDIAC",
    "RUA-REF": "R ALVORADA",
    "NUM": "00178",
    "TEL1-REF": "032020263",
    "TEL2-REF": "032232276",
    "TIPO-REF": "SERVICOS DE DIAGNOSTICO",
    "ESPECIALIDADE": "TOMOGRAFIA COMPUTADORIZADA"

}

/*
    "UF": "AC",
    "CIDADE": "RIO BRANCO",
    "BAIRRO-REF": "BOSQUE",
    "NOME-REF": "CEDIAC",
    "RUA-REF": "R ALVORADA",
    "NUM": "00178",
    "TEL1-REF": "032020263",
    "TEL2-REF": "032232276",
    "TIPO-REF": "SERVICOS DE DIAGNOSTICO",
    "ESPECIALIDADE": "TOMOGRAFIA COMPUTADORIZADA"
*/